### ISSUE TITLE
error: identifier "__builtin_ia32_rndscalesd_round" is undefined

### ISSUE THREAD

**Issue by damionfan** [scale-snu/ckks-gpu-core#1]
When  I implement “”cmake --build build -j“”

`[  5%] Building CXX object _deps/rmm-build/CMakeFiles/rmm.dir/__/cnmem-src/src/cnmem.cpp.o
[ 10%] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 15%] Linking CXX shared library librmm.so
[ 15%] Built target rmm
[ 20%] Building CUDA object CMakeFiles/DeviceFunctions.dir/src/public/DeviceVector.cu.o
[ 25%] Building CUDA object CMakeFiles/DeviceFunctions.dir/src/public/CudaHelper.cu.o
[ 30%] Building CUDA object CMakeFiles/DeviceFunctions.dir/src/public/Context.cu.o
[ 35%] Building CUDA object CMakeFiles/DeviceFunctions.dir/src/public/MultPtxtBatch.cu.o
[ 40%] Building CUDA object CMakeFiles/DeviceFunctions.dir/src/public/NttImple.cu.o
/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(9146): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(9155): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(14797): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h(14806): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512dqintrin.h(1365): error: identifier "__builtin_ia32_fpclassss" is undefined

/usr/lib/gcc/x86_64-linux-gnu/9/include/avx512dqintrin.h(1372): error: identifier "__builtin_ia32_fpclasssd" is undefined`

can you give me some advice?

**Comment by damionfan** [comment]
-- The CUDA compiler identification is NVIDIA 11.1.74
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-11.1/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDAToolkit: /usr/local/cuda-11.1/include (found version "11.1.74") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Thrust: /usr/local/cuda/include  
-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python: /usr/bin/python3.6 (found version "3.6.9") found components: Interpreter 
-- RMM: Enabling the GLIBCXX11 ABI
-- Build spdlog: 1.6.0
-- Build type: Release
-- Using Nvidia Tools Extension
-- Configuring done
-- Generating done
-- Build files have been written to: /home/part2/old/ckks-gpu-core/build

**Comment by wkjung** [comment]
I removed the unused header in d4d99994f9f76f03d105ac22851e4eec64f2c273. Would you try again?

**Comment by damionfan** [comment]
Yes, it passed.However, I encountered another mistake!
`[ 90%] Building CXX object unittest/CMakeFiles/FusionTest.dir/public/FusionTest.cpp.o
[ 95%] Linking CXX executable Benchmark
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
benchmark/CMakeFiles/Benchmark.dir/build.make:100: recipe for target 'benchmark/Benchmark' failed
make[2]: *** [benchmark/Benchmark] Error 1
CMakeFiles/Makefile2:475: recipe for target 'benchmark/CMakeFiles/Benchmark.dir/all' failed
make[1]: *** [benchmark/CMakeFiles/Benchmark.dir/all] Error 2`

**Comment by damionfan** [comment]
[ 80%] Built target DeviceFunctions
[ 85%] Building CXX object benchmark/CMakeFiles/Benchmark.dir/Benchmark.cpp.o
[ 90%] Building CXX object unittest/CMakeFiles/FusionTest.dir/public/FusionTest.cpp.o
[ 95%] Linking CXX executable Benchmark
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
benchmark/CMakeFiles/Benchmark.dir/build.make:100: recipe for target 'benchmark/Benchmark' failed
make[2]: *** [benchmark/Benchmark] Error 1
CMakeFiles/Makefile2:475: recipe for target 'benchmark/CMakeFiles/Benchmark.dir/all' failed
make[1]: *** [benchmark/CMakeFiles/Benchmark.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable FusionTest
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
unittest/CMakeFiles/FusionTest.dir/build.make:102: recipe for target 'unittest/FusionTest' failed
make[2]: *** [unittest/FusionTest] Error 1
CMakeFiles/Makefile2:265: recipe for target 'unittest/CMakeFiles/FusionTest.dir/all' failed
make[1]: *** [unittest/CMakeFiles/FusionTest.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
root@d5c20dd846a0:/home/part2/old/ckks-gpu-core# /usr/bin/ld -v
GNU ld (GNU Binutils for Ubuntu) 2.30

**Comment by damionfan** [comment]
I remove the -lcuda

**Comment by wkjung** [comment]
Problem solved?

**Comment by damionfan** [comment]
Yes! Thank your!
