### ISSUE TITLE
error:no kernel image is available for execution on the device'

### ISSUE THREAD

**Issue by damionfan** [scale-snu/ckks-gpu-core#2]
Running main() from /home/fsy/fhe/ckks-gpu-core/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 8 tests from Params/FusionTest
[ RUN      ] Params/FusionTest.ModUp/0
Cuda failure /home/fsy/fhe/ckks-gpu-core/src/public/Context.cu:361: 'no kernel image is available for execution on the device'

**Comment by wkjung** [comment]
Does your GPU meet the compute capability over 7.0?
