### ISSUE TITLE
How to test the performance of complete bootstrapping

### ISSUE THREAD

**Issue by KaneX** [scale-snu/ckks-gpu-core#3]
Hello,

I am interested in your paper and would like to reproduce your result of bootstrapping. It seems that the test cases provided in Run.ipynb demonstrate the performance of some components in key switching and bootstrapping. 

Is it possible for me to test the performance of fully-functioning bootstrapping (perhaps key switching as well) using your source code? Hopefully I can get the speed-up vs CPU on my own machine, as you have demonstrated in Table 3 of the paper.

**Comment by wkjung** [comment]
Hi Kanex.

Unfortunately, the fully-functioning bootstrapping code is currently not available.
Because the library used in the paper are proprietary, we provide only the core functions required to compose the fully-functioning operations (bootstrapping and other HE operations).

**Comment by zzwplus** [comment]
Hi wkjung.

I can't find any function for the multiplication between **ciphertexts**. Is it because it belongs to the proprietary library?

If yes, then Is there any way for me to realize this function?

**Comment by wkjung** [comment]
Hi @zzwplus .

Yes, that's the reason.

You should implement on your own. At least you need to implement tensoring function. And with the provided functions,  you will be able to implement the ciphertext multiplication by composing them.

**Comment by zzwplus** [comment]
> Hi @zzwplus .
> 
> Yes, that's the reason.
> 
> You should implement on your own. At least you need to implement tensoring function. And with the provided functions, you will be able to implement the ciphertext multiplication by composing them.

Hi @wkjung .

Thanks for your reply. And I will try to do it according to your suggestion.

**Comment by zzwplus** [comment]
Hi @wkjung .

In your article **Accelerating Fully Homomorphic Encryption Through Architecture-Centric Analysis and Optimization**, I had noticed that "**Full-RNS variants do not require CRT and iCRT**". 

So, does that mean no need to consider **primes {pj |0≤j<m}** for implementing NTT&iNTT?

**Comment by wkjung** [comment]
@zzwplus 
I don't fully understand your questions; the temporary moduli (or, special moduli) used in key-switching also requires corresponding NTT/iNTT. 
btw, because that is entirely separate issue, please contact me via email or open as another issue.
